Git Pull Check added

diff --git a/Hooks/SXR/SXR-Benchmark/pre-commit b/Hooks/SXR/SXR-Benchmark/pre-commit
--- a/Hooks/SXR/SXR-Benchmark/pre-commit
+++ b/Hooks/SXR/SXR-Benchmark/pre-commit
@@ -1,30 +1,163 @@
 #!/bin/sh
+#Project: AP.SXR.Benchmarks
+#Constants
 RED='\033[0;31m'
 GREEN='\033[0;32m'
 BLUE='\033[0;34m'
 YELLOW='\033[0;33m'
 NC='\033[0m' # No Color
 TARGET_PROJECT=./Solutions/WebApi/WebApi.csproj
-NUGET_SOURCE=https://api.nuget.org/v3/index.json
-TOOLS_FOLDER="c:\\\tools"
-GITLEAK_PATH="c:\\tools\\gitleaks.exe"
-GITLEAK_DOWNLOAD_URL="https://github.com/gitleaks/gitleaks/releases"
+REPO_URL=$(git config --get remote.origin.url)
+REPO_NAME=$(basename -s .git "$REPO_URL")
+GIT_DIR=$(basename "$(git rev-parse --show-toplevel)")
+GIT_BRANCH=$(git rev-parse --abbrev-ref HEAD)
+# Variables 
 staged_files=$(git diff --cached --name-only --diff-filter=ACMR)
+total_secrets=0
+printf "\n${YELLOW}==================================================================================${NC}"
+printf "\n\t\t\t RUNNING PRE-COMMIT HOOK ${NC}"		
+printf "\n${YELLOW}==================================================================================${NC}"
+printf "\n\tProject: $REPO_NAME\n"
+printf "\n\tAuthor: AlixPartners\n"
+printf "\n\tRepo: $REPO_NAME\n"
+printf "\n\tRepo URL:  $REPO_URL\n"
+printf "\n\tRepo Directory:  $PWD.Path\n"
+printf "\n\tBranch: $GIT_BRANCH\n"
 
 printf "\n${YELLOW}==================================================================================${NC}"
-printf "\n\t\t\tRunning pre-commit checks${NC}"		
+printf "\n\t\t\tChecking for staged files${NC}"		
 printf "\n${YELLOW}==================================================================================${NC}"
-printf "\n\t\t\tChecking Python folder ${NC}"		
-printf "\n${YELLOW}----------------------------------------------------------------------------------${NC}\n"
-PY_VER=$(py -3 -c "import sys; print(f'{sys.version_info.major}{sys.version_info.minor}')")
-CODESPELL_PATH="$APPDATA\\Python\\Python$PY_VER\\Scripts\\codespell.exe"
-printf "\n Python [Version:$PY_VER] Installed on System.\n"
+
+if [[ -z "$staged_files" ]]; then
+    printf "\nNo staged files found."
+    printf "\nPlease stage the required files."
+    printf "\nExiting.\n"
+    exit 1
+else
+    printf "\n\tList of Staged files detected:\n"
+    printf "\n$staged_files\n"
+fi
+
+printf "\n${YELLOW}==================================================================================${NC}"
+printf "\n\t\tCheck if remote branch has changes not pulled yet                                  ${NC}"		
+printf "\n${YELLOW}==================================================================================${NC}"
+
+git fetch origin > /dev/null 2>&1
+LOCAL=$(git rev-parse @)
+REMOTE=$(git rev-parse @{u} 2>/dev/null)
+BASE=$(git merge-base @ @{u} 2>/dev/null)
+if [ $? -ne 0 ]; then
+    printf "\n ${YELLOW} No upstream branch set for current branch.${NC}"
+    printf "\n ${YELLOW} Use: git push --set-upstream origin <branch-name>${NC}"
+    exit 1
+fi
+if [ "$LOCAL" = "$REMOTE" ]; then
+	printf "\n ${GREEN} Local branch is up to date with remote.${NC}"
+elif [ "$LOCAL" = "$BASE" ]; then
+	printf "\n\t${RED}Your local branch is behind remote.${NC}"
+    printf "\n\t${RED}Please run: git pull.${NC}"
+    printf "\n\t${RED}Exiting.\n${NC}"
+    exit 1
+elif [ "$REMOTE" = "$BASE" ]; then	
+    printf "\n\t${RED}Local branch is ahead of remote (not pushed yet).${NC}"
+else
+    printf "\n\t${RED}Local and remote have diverged! You need to pull & rebase.${NC}"
+    exit 1
+fi
+
+
+printf "\n${YELLOW}==================================================================================${NC}"
+printf "\n\t\t\t Detect merge conflict markers                                                       ${NC}"		
+printf "\n${YELLOW}==================================================================================${NC}"
+
+for file in $staged_files; do
+	  printf "\n\t Scanning: ${file} ${NC}"
+	  printf "\n-----------------------------------------------------------------------------------\n"
+    if git show :$file | grep -q -E '^(<<<<<<<|=======|>>>>>>>)'; then
+		printf "\n\t${RED}Commit aborted ${NC}"
+		printf "\n\t${RED}Merge conflict markers detected in ${file} ${NC}"
+		printf "\n\t${RED}Please resolve the conflicts before committing.${NC}"
+		printf "\n\t${RED}Exiting.\n${NC}"
+		exit 1
+    fi
+done
+printf "\n\t${GREEN} No conflict markers found. Proceeding for next Check."
+
+
+printf "\n${YELLOW}==================================================================================${NC}"
+printf "\n\t\tChecks for Creds                                                    "
+printf "\n${YELLOW}==================================================================================${NC}"
+printf "\nRunning pre-commit Checks for Creds..."
+
+
+found_secrets=0
+# Array of keywords/patterns to search for (customize this list)
+sensitive_patterns=(
+    "API_KEY="
+    "SECRET_KEY="
+    "PASSWORD="
+    "ACCESS_TOKEN="
+    "AUTH_TOKEN="
+    "PRIVATE_KEY"
+    "client_secret"
+    "jwt_secret"
+    # Add more patterns as needed
+)
+
+# Function to scan a file for sensitive patterns
+scan_for_secrets() {
+    printf "\nScaning for secrets/creds in '$file'..."
+    local file="$1"
+    local pattern
+    local line_number=1
+	local number_of_secrets=0
+	while IFS= read -r line; do
+		# printf "$line"
+		for pattern in "${sensitive_patterns[@]}"; do
+            if [[ "$line" == *"$pattern"* ]]; then
+               printf "\n${RED}ERROR: Potential secret found in '$file' on line $line_number: '$line'"
+			   #number_of_secrets =number_of_secrets + 1
+			   # Indicate a secret was found
+             fi
+			 line_number=$((line_number + 1))
+        done
+	done < "$file"
+	if [[ "$number_of_secrets" -gt 0 ]]; then
+		printf "\n${RED}Secret(s) found in the file [$file] at Line $line_number. ${NC}"
+	else 
+		printf "\n${GREEN}No secrets found in the file [$file].${NC}"
+	fi
+    return $number_of_secrets # No secrets found in the file
+}
+#printf "\nChecking for secrets..."
+# Scan staged files for potential secrets
+ 
+ for file in $staged_files; do
+	#printf "Checking File '$file' Started"
+    if scan_for_secrets $file; then
+        total_secrets=0
+    fi
+    #printf "\nChecking File $file Completed"
+ done
+ printf "\nNumber of Secret/Creds Found: $total_secrets"
+ printf "\n${GREEN}Checking for secrets completed...${NC}"
+ 
+if [ $total_secrets -gt 0 ]; then
+	printf "\n${YELLOW}-------------------------------------------------------------------------------${NC}"
+    printf "\nCred Scan Result${NC}"
+	printf "\n${YELLOW}-------------------------------------------------------------------------------${NC}"
+	printf "\nERROR: Potential secrets found in staged files. Please review and remove them before committing.${NC}"
+	printf "\nCreds Check completed with Potential secrets found in changeset.${NC}"
+	printf "\n${YELLOW}-------------------------------------------------------------------------------"
+    exit 1
+fi
+printf "\n${GREEN}Creds Check passed.${NC}"
+
+
 printf "\n${YELLOW}==================================================================================${NC}"
 printf "\n\t\t\tChecks for Spelling Mistakes                                                         ${NC}"
 printf "\n${YELLOW}==================================================================================${NC}"
-
 printf "\nChecking codespell...\n"
-
 if [ -x "$CODESPELL_PATH" ]; then
     printf "\n${GREEN} CodeSpell [Spelling Check Tool] installed on systems.${NC}\n"
 else
@@ -33,8 +166,6 @@ else
     python.exe -m pip install --force-reinstall codespell
 	printf "\n----------------------------------------------------------------------------------${NC}"
 fi
-
-
 printf "\nRunning Spelling Mistakes Check on Staged files...\n"
 for file in $staged_files; do
 	printf "\nFile:${YELLOW}'$file'${NC}\n"
@@ -44,16 +175,11 @@ for file in $staged_files; do
 	  printf "\n----------------------------------------------------------------------------------${NC}"
 	fi
 done
-
-
 printf "\nSpelling Mistakes Scanning completed.\n\n"
-
 
 printf "\n${YELLOW}==================================================================================${NC}"
 printf "\n\tChecks for Creds/Tokens/Other potential confidential Information                     ${NC}"
 printf "\n${YELLOW}==================================================================================${NC}\n"
-
-
 if [ -x "$GITLEAK_PATH" ]; then
     printf "\n${GREEN} gitleaks [Creds Check Tool] installed on systems.${NC}\n"
 else
@@ -66,24 +192,16 @@ else
 	printf "\n4. Run Commit Commans											                    ${NC}"
 	printf "\n----------------------------------------------------------------------------------${NC}"
 fi
-
-
-
 printf "\nRunning gitleaks on Staged files...\n"
 c:\\tools\\gitleaks detect --verbose --redact
-
 if [ $? -ne 0 ]; then
   printf "\n${RED}gitleaks found potential secrets. Please fix before committing.${NC}\n"
   #exit 1
 fi
-
 printf "\nSecrets [gitleaks] scanning completed.\n\n"
-
 printf "\n${YELLOW}==================================================================================${NC}"
 printf "\n\t\t\tRunning preliminary checks (e.g., build)...						${NC}"
 printf "\n${YELLOW}==================================================================================${NC}"
-
-# dotnet build ./Solutions/AP.Quickstrike.Functions/AP.Quickstrike.Functions.csproj -clp:ErrorsOnly
 
 printf "\nBuilding Web Project [AP.QuickStrike.Web]."
 dotnet build ${TARGET_PROJECT} -clp:ErrorsOnly
@@ -91,42 +209,37 @@ if [ $? -ne 0 ]; then
     printf "\nBuild failed. Please fix the errors before committing."
     exit 1
 fi
-
 printf "\nRunning preliminary check passed."
 
 
 
 printf "\n${YELLOW}==================================================================================${NC}"
-printf "\n\t\t\tRunning Packages Analysis  			           "
+printf "\n\t\t\t Running Packages Analysis  [Microsoft dotnet tool]	                                      "
 printf "\n${YELLOW}==================================================================================${NC}"
 
 printf "\nChecking for deprecated Packages...."
-
 dotnet list ${TARGET_PROJECT} package --deprecated  
 
 printf "\nChecking for vulnerable Packages...."
-
-dotnet list ${TARGET_PROJECT} package --vulnerable  
+dotnet list ${TARGET_PROJECT} package --vulnerable
+  
 printf "\nChecking for outdated Packages...."
-
 dotnet list ${TARGET_PROJECT} package --outdated  
 
 printf "\n${YELLOW}==================================================================================${NC}"
-printf "\n\t\t\tRunning static analysis 			           "
+printf "\n\t\t\t Running static analysis 			           "
 printf "\n${YELLOW}==================================================================================${NC}"
 
+printf "\nRunningStatic Analysis using Locally Hosted SonarQube."
+Powershell ./Solutions/sonar-scan.bat
 printf "\nStatic Analysis using Microsoft.DevSkim.CLI."
 
 printf "\nInstalling Microsoft.DevSkim.CLI.......\n"
 dotnet tool install --global Microsoft.CST.DevSkim.CLI 
 
 printf "\nRunning Microsoft.DevSkim.CLI analyzer"
-
 timestamp=$(date +"%Y%m%d_%H%M%S")
 log_file="DevSkim_$timestamp.log"
-
-
-#devskim analyze --source-code ./Solutions --output-format sarif --severity Critical 
 
 printf "\n${YELLOW}-------------------------------------------------------------------------------${NC}"
 printf "\nSAST: Microsoft.DevSkim Scan results available in $log_file${NC}"
@@ -136,10 +249,8 @@ devskim analyze --source-code ./Solutions --output-format sarif --severity Criti
 
 printf "\nStatic Analysis completed, Please check for vulnerabilities."
 
-
 printf "\n${YELLOW}==================================================================================${NC}"
 printf "\n\t\t\tAll Pre-commit checks passed.	${NC}"					 												
 printf "\n${YELLOW}==================================================================================${NC}"
-
 
 exit 0
